/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Iloczyn */

#ifndef _Included_example_Iloczyn
#define _Included_example_Iloczyn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_Iloczyn
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_example_Iloczyn_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     example_Iloczyn
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_example_Iloczyn_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     example_Iloczyn
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_Iloczyn_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
